Workaround for expired credentials
I was trying to use creds.refresh() to refresh expired credentials. But
every time I had expired credentials I got the stack trace shown below
instead of renewed credentials. Either Google's refresh() function is
broken (very unlikely), I am using it wrong (likely), or I am failing
to understand some important detail (virtually certain).

As a workaround, I am deleting the expired credential and letting them
be renewed via the web-page redirect method. I suspect there may be two
forms of expiration, a short term and a long term version. If true,
then the short term version is probably what refresh() was meant for.

Traceback (most recent call last):
  File "/home/chuckw/cctools/ccct/./ccct", line 469, in <module>
    main()
  File "/home/chuckw/cctools/ccct/./ccct", line 458, in main
    _get_google_creds()
  File "/home/chuckw/cctools/ccct/./ccct", line 116, in _get_google_creds
    creds.refresh(Request())
  File "/usr/local/lib/python3.11/site-packages/google/oauth2/credentials.py", line 391, in refresh
    ) = reauth.refresh_grant(
        ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/google/oauth2/reauth.py", line 365, in refresh_grant
    _client._handle_error_response(response_data, retryable_error)
  File "/usr/local/lib/python3.11/site-packages/google/oauth2/_client.py", line 72, in _handle_error_response
    raise exceptions.RefreshError(
google.auth.exceptions.RefreshError: ('invalid_grant: Token has been expired or revoked.', {'error': 'invalid_grant', 'error_description': 'Token has been expired or revoked.'})